# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #     monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
         - targets: ['localhost:9090']

  # - job_name: 'cadvisor'

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 15s

  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'node-exporter'

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 15s
  
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # - job_name: "ssh-exporter"
  #   scrape_interval: 15s
  #   static_configs:
  #       - targets: ['ssh-exporter:9312']

  - job_name: "ssh" 
    metrics_path: /ssh
    static_configs:
    - targets:
      - <Target Address>:22
      labels:
        module: capture
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: ssh-exporter:9312
    - source_labels: [module]
      target_label: __param_module
    metric_relabel_configs:
    - regex: "^(module)$"
      action: labeldrop
  
  - job_name: ssh-metrics
    metrics_path: /metrics
    static_configs:
    - targets:
      - ssh-exporter:9312
